language: python

python:
    - 2.6
    - 2.7
    - 3.4

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

services:
  - redis-server

install:
    - pip install -r requirements-tracker.txt
    - pip install selenium

script:
    - NO_LIVE_SERVICE_TEST=1 nosetests terroroftinytown/client/ terroroftinytown/services/
    - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then DISPLAY=:99.0 nosetests terroroftinytown/tracker/; fi

